#ifdef __linux__
#include "EngineApplication_Linux.h"
#include "Engine/_Module/_AutoGenerated/TypeInfo/TypeRegistration.h"

#include <SDL3/SDL.h>

//-------------------------------------------------------------------------

namespace EE
{
    StandaloneEngine::StandaloneEngine( TFunction<bool( EE::String const& error )>&& errorHandler )
        : Engine( eastl::forward<TFunction<bool( EE::String const& error )>&&>( errorHandler ) )
    {
        m_modules.emplace_back( EE::New<GameModule>() );
    }

    void StandaloneEngine::RegisterTypes()
    {
        TypeSystem::Reflection::RegisterTypes( *m_pTypeRegistry );
    }

    void StandaloneEngine::UnregisterTypes()
    {
        TypeSystem::Reflection::UnregisterTypes( *m_pTypeRegistry );
    }

    void StandaloneEngine::PostInitialize()
    {
        m_pGameViewport = m_pEntityWorldManager->GetGameWorld()->CreateViewport( m_pRenderWindow );
        Float2 const newViewportDimensions( m_pRenderWindow->GetSwapchainSize() );
        m_pGameViewport->Resize( Float2::Zero, newViewportDimensions );
    }

    void StandaloneEngine::PreShutdown()
    {
        if ( m_pGameViewport != nullptr )
        {
            m_pEntityWorldManager->GetGameWorld()->DestroyViewport( m_pGameViewport );
        }
    }

    void StandaloneEngine::ResizeMainWindow( Int2 newMainWindowDimensions )
    {
        Engine::ResizeMainWindow( newMainWindowDimensions );

        //-------------------------------------------------------------------------

        if ( m_pGameViewport != nullptr )
        {
            Float2 const newWindowDimensions = Float2( newMainWindowDimensions );
            Int2 const newViewportDimensions( Math::CeilingToInt32( newWindowDimensions.m_x ), Math::CeilingToInt32( newWindowDimensions.m_y ) ); // Ensure we also have valid dimensions
            EE_ASSERT( newViewportDimensions.m_x > 0 && newViewportDimensions.m_y > 0 );
            m_pGameViewport->Resize( Float2::Zero, newViewportDimensions );
        }
    }

    //-------------------------------------------------------------------------

    // No HINSTANCE, and no icon or splash screen resource IDs. The Windows build loads both from
    // Code/Applications/Engine/Win32/, which holds a .ico and a .bmp reachable only through a
    // .rc file. Phase 6 says not to parse those, and LinuxApplication takes file paths that may
    // be null, so the Linux engine starts with neither. See P6.2.
    EngineApplication::EngineApplication()
        : LinuxApplication( "Esoterica Engine" )
        , m_engine( TFunction<bool( EE::String const& error )>( [this] ( String const& error )-> bool { return FatalError( error ); } ) )
    {}

    void EngineApplication::ResizeMainWindow( Int2 const& newWindowSize )
    {
        m_engine.ResizeMainWindow( newWindowSize );
    }

    void EngineApplication::ProcessInputEvent( SDL_Event const& event )
    {
        // The event travels by pointer, because GenericMessage is four uint64_t and an SDL_Event
        // is 128 bytes. This is sound only because ForwardInputMessageToInputDevices dispatches
        // synchronously, from inside LinuxApplication's event loop, while the event is still on
        // the stack. **Nothing may queue this message for later.** The Win32 sibling passes an
        // HRAWINPUT handle through the same field. See the P6.4 entry in Docs/Linux/Progress.md.
        m_engine.GetInputSystem()->ForwardInputMessageToInputDevices( { (uint64_t) &event, 0, 0, 0 } );
    }

    bool EngineApplication::Initialize( int32_t argc, char** argv )
    {
        if ( !m_engine.Initialize( argc, argv, m_windowSize ) )
        {
            return FatalError( "Failed to initialize engine" );
        }

        return true;
    }

    bool EngineApplication::Shutdown()
    {
        return m_engine.Shutdown();
    }

    bool EngineApplication::ApplicationLoop()
    {
        return m_engine.Update();
    }
}

//-------------------------------------------------------------------------

// _tWinMain becomes main. __argc and __argv have no equivalent and no need for one: argc and
// argv arrive as arguments here, where the Windows entry point has to fetch them from the CRT.
int main( int argc, char** argv )
{
    int result = 0;
    {
        EE::ApplicationGlobalState globalState;
        EE::EngineApplication engineApplication;
        result = engineApplication.Run( argc, argv );
    }

    return result;
}

#endif
