#ifdef __linux__
#include "ResourceServerApplication_Linux.h"
#include "EngineTools/_Module/_AutoGenerated/TypeInfo/TypeRegistration.h"
#include "EngineTools/Core/SystemDialogs.h"
#include "Base/Time/Timers.h"
#include "Base/Threading/Threading.h"
#include "Base/FileSystem/FileSystemUtils.h"
#include "Base/Platform/Platform.h"
#include "Base/Settings/IniFile.h"
#include "Base/Render/Settings/Settings_Render.h"
#include "Base/Profiling.h"

#include <fcntl.h>
#include <stdlib.h>
#include <sys/file.h>
#include <unistd.h>

// No <SDL3/SDL.h>. The minimized check goes through LinuxApplication::IsMainWindowMinimized, so
// the Resource Server reaches SDL only through Esoterica.Base and needs no SDL3 include path.

//-------------------------------------------------------------------------

namespace EE
{
    // No HINSTANCE, and no icon resource ID. The Windows build takes IDI_RESOURCESERVER from
    // Code/Applications/ResourceServer/Resources/Resource.h, which only a .rc file resolves.
    // Same choice as EngineApplication_Linux and EditorApplication_Linux.
    //
    // The Borderless flag is kept: ResourceServerUI draws its own title bar, and
    // LinuxApplication's BorderlessWindowHitTest calls GetBorderlessTitleBarInfo through
    // SDL_SetWindowHitTest. StartMinimized is dropped - see the header.
    ResourceServerApplication::ResourceServerApplication()
        : LinuxApplication( "Esoterica Resource Server", nullptr, nullptr, TBitFlags<InitOptions>( LinuxApplication::InitOptions::Borderless ) )
        , m_resourceServer( m_typeRegistry )
        , m_resourceServerUI( m_resourceServer )
    {}

    void ResourceServerApplication::ResizeMainWindow( Int2 const& newWindowSize )
    {
        if ( m_renderWindow.GetSwapchainSize() != newWindowSize )
        {
            m_renderSystem.WaitGraphicsQueueIdle();
            m_renderWindow.ResizeSwapchain( m_renderSystem.GetContextRHI(), m_renderSystem.GetGraphicsQueue(), m_renderSystem.GetComputeQueue(), newWindowSize );
        }
    }

    bool ResourceServerApplication::OnUserExitRequest()
    {
        // Allow exiting immediately if there are no connected clients
        if ( m_resourceServer.GetNumConnectedClients() == 0 )
        {
            return true;
        }

        //-------------------------------------------------------------------------

        // Confirm exit if there are still connected clients, as the Win32 sibling does.
        //
        // ShowEx rather than Confirmation, because the three results have to be told apart.
        // Confirmation collapses "the user said No" and "no dialog could be shown" into one false,
        // so a server with no display would refuse every exit and trap the user in a window that
        // will not close. ShowEx returns Cancel for that case, and exiting is the right answer.
        MessageDialog::Result const result = MessageDialog::ShowEx( Severity::Warning, MessageDialog::Type::YesNo, "Resource Server", "There are still connected clients!\nAre you sure you want to exit the Resource Server?" );
        return result != MessageDialog::Result::No;
    }

    //-------------------------------------------------------------------------

    // argc and argv are unnamed because the body ignores them, exactly as upstream's Win32 version
    // does. The Resource Server takes no command line arguments; the signature is the base class's.
    bool ResourceServerApplication::Initialize( int32_t /* argc */, char** /* argv */ )
    {
        TypeSystem::Reflection::RegisterTypes( m_typeRegistry );

        FileSystem::Path const iniFilePath = FileSystem::GetCurrentProcessPath().Append( "Esoterica.ini" );
        IniFile iniFile;
        if ( !iniFile.Load( iniFilePath ) )
        {
            InlineString const errorMessage( InlineString::CtorSprintf(), "Failed to load settings from INI file: %s", iniFilePath.c_str() );
            return FatalError( errorMessage.c_str() );
        }

        // m_renderSettings, not a local. RenderSystem::Initialize keeps its address and reads it
        // every frame; see the note in the header.
        m_renderSettings.LoadSettings( m_typeRegistry, iniFile );

        // The Win32 sibling derives the dimensions from m_windowRect. LinuxApplication keeps the
        // size and the position apart, and m_windowSize is already in pixels, which is the unit
        // the swapchain wants.
        m_renderSystem.Initialize( m_renderSettings );

        m_renderWindow.SetNativeWindowHandle( Platform::GetMainWindowHandle() );
        m_renderWindow.ResizeSwapchain( m_renderSystem.GetContextRHI(), m_renderSystem.GetGraphicsQueue(), m_renderSystem.GetComputeQueue(), m_windowSize );

        m_renderSystem.RegisterRenderWindow( &m_renderWindow );

        //-------------------------------------------------------------------------

        if ( !m_resourceServer.Initialize( iniFilePath ) )
        {
            return FatalError( "Resource server failed to initialize!" );
        }

        //-------------------------------------------------------------------------

        m_renderSystem.StartResourceUpdates( true );

        m_imguiSystem.Initialize();
        m_imguiRenderer.Initialize( &m_renderWindow, &m_renderSystem );

        m_resourceServerUI.Initialize( m_imguiRenderer.GetImageCache() );

        m_renderSystem.SubmitResourceUpdates( true );

        return true;
    }

    bool ResourceServerApplication::Shutdown()
    {
        // The Win32 sibling asserts WasInitialized() here, and that assert is wrong on both
        // platforms: Run() calls Shutdown() when Initialize() fails, before m_initialized is
        // set. It fires whenever the server cannot start - a second instance losing the race
        // for port 5556 is the ordinary case. Return early instead, because the members below would
        // otherwise be torn down without having been created.
        if ( !WasInitialized() )
        {
            return true;
        }

        m_renderSystem.WaitAllQueuesIdle();

        m_renderSystem.UnregisterRenderWindow( &m_renderWindow );
        m_renderWindow.DestroySwapchain( m_renderSystem.GetContextRHI() );

        m_resourceServerUI.Shutdown();

        m_imguiRenderer.Shutdown();
        m_imguiSystem.Shutdown();

        m_renderSystem.Shutdown();

        Render::RHI::ReportDeviceMemoryLeaks();

        //-------------------------------------------------------------------------

        m_resourceServer.Shutdown();

        TypeSystem::Reflection::UnregisterTypes( m_typeRegistry );

        return true;
    }

    //-------------------------------------------------------------------------

    bool ResourceServerApplication::ApplicationLoop()
    {
        Milliseconds deltaTime = 0;
        {
            ScopedTimer<PlatformClock> frameTimer( deltaTime );

            // Update resource server
            //-------------------------------------------------------------------------

            {
                EE_PROFILE_SCOPE( "Resource Server Update" );

                m_resourceServer.Update();

                // Sleep when idle to reduce CPU load
                if ( !m_resourceServer.IsBusy() )
                {
                    Threading::Sleep( 1 );
                }
            }

            // The Win32 sibling updates a taskbar overlay icon and a tray icon from the busy
            // state here. Neither exists on Linux, so the busy state is only read for the sleep
            // above.

            // Draw UI
            //-------------------------------------------------------------------------

            {
                EE_PROFILE_SCOPE( "Resource Server UI" );

                if ( !IsMainWindowMinimized() )
                {
                    m_imguiSystem.StartFrame( m_deltaTime );
                    m_resourceServerUI.Draw();
                    m_imguiSystem.EndFrame();

                    ImGui::Render();

                    m_renderSystem.WaitForFrameStart();

                    m_renderSystem.StartResourceUpdates( false );
                    m_imguiRenderer.UpdateDeviceResources();
                    m_renderSystem.SubmitResourceUpdates( false );

                    m_renderSystem.StartFrame();
                    m_imguiRenderer.StartFrame();
                    m_imguiRenderer.SubmitFrame( true );
                    m_renderSystem.SubmitFrame();

                    m_imguiRenderer.EndFrame();
                }
            }
        }

        m_deltaTime = deltaTime;
        EngineClock::Update( deltaTime );

        return true;
    }
}

//-------------------------------------------------------------------------
// Single instance
//-------------------------------------------------------------------------
// The Windows entry point creates a named mutex and refuses to start twice. The same guard, and not
// optional: a second server loses the race for port 5556, and ResourceServerContext::Initialize then
// returns false having already allocated its CompilerRegistry, so the destructor asserts. The mutex
// is what stops Windows ever reaching that.
//
// flock, not a PID file: the kernel drops the lock however the process dies, so a crashed server
// never leaves a stale lock behind.

static int g_singleInstanceLockFileDescriptor = -1;

static bool TryAcquireSingleInstanceLock()
{
    // XDG_RUNTIME_DIR is per-user and cleaned on logout. /tmp is the fallback, with the user ID
    // in the name so that two users on one machine do not fight over one file.
    char lockFilePath[256];
    char const* pRuntimeDirectory = getenv( "XDG_RUNTIME_DIR" );
    if ( pRuntimeDirectory != nullptr && pRuntimeDirectory[0] != 0 )
    {
        snprintf( lockFilePath, sizeof( lockFilePath ), "%s/EsotericaResourceServer.lock", pRuntimeDirectory );
    }
    else
    {
        snprintf( lockFilePath, sizeof( lockFilePath ), "/tmp/EsotericaResourceServer.%u.lock", (uint32_t) getuid() );
    }

    g_singleInstanceLockFileDescriptor = open( lockFilePath, O_RDWR | O_CREAT | O_CLOEXEC, 0600 );
    if ( g_singleInstanceLockFileDescriptor < 0 )
    {
        // Cannot tell whether another server is running, so do not block this one.
        return true;
    }

    if ( flock( g_singleInstanceLockFileDescriptor, LOCK_EX | LOCK_NB ) != 0 )
    {
        close( g_singleInstanceLockFileDescriptor );
        g_singleInstanceLockFileDescriptor = -1;
        return false;
    }

    return true;
}

static void ReleaseSingleInstanceLock()
{
    if ( g_singleInstanceLockFileDescriptor >= 0 )
    {
        flock( g_singleInstanceLockFileDescriptor, LOCK_UN );
        close( g_singleInstanceLockFileDescriptor );
        g_singleInstanceLockFileDescriptor = -1;
    }
}

//-------------------------------------------------------------------------

// _tWinMain becomes main, as in EngineApplication_Linux.cpp and EditorApplication_Linux.cpp.
int main( int argc, char** argv )
{
    if ( !TryAcquireSingleInstanceLock() )
    {
        // stderr, not a dialog. The Windows version shows a MessageBox; this is launched from a
        // terminal or by the editor, and SDL is not initialized yet in either case.
        fprintf( stderr, "Only a single instance of the Resource Server is allowed to run!\n" );
        return -1;
    }

    int result = 0;
    {
        EE::ApplicationGlobalState globalState;
        EE::ResourceServerApplication resourceServerApplication;
        result = resourceServerApplication.Run( argc, argv );
    }

    ReleaseSingleInstanceLock();

    return result;
}

#endif
