#!/usr/bin/env bash
#
# Runs the reflection code generator, which every other build step depends on.
#
#   ./RunReflection.sh              generate what is missing or out of date
#   ./RunReflection.sh --rebuild    regenerate everything
#   ./RunReflection.sh --clean      delete the generated output
#
# Mirrors RunReflection.bat and the build, rebuild and clean targets of
# Code/Scripts/Reflect/Reflect.nmake.
#
# Like the .bat, this does not build the Reflector for you. Build it first:
#
#   python3 Code/Scripts/NinjaGen/NinjaGen.py
#   ninja -f Build/Linux/Esoterica.ninja Build/Linux_Release/Esoterica.Applications.Reflector
#
# Reflect.nmake invokes msbuild to build the Reflector before each run. That is left out on
# purpose: it hides which step failed, and the ninja command above is one line.

set -euo pipefail

REPO_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SOLUTION_PATH="${REPO_ROOT}/Esoterica.slnx"

REFLECTOR_ARGS=()
REFLECTOR_EXE="${REPO_ROOT}/Build/Linux_Release/Esoterica.Applications.Reflector"

#-------------------------------------------------------------------------

# Reflect.nmake empties the autogenerated directories itself before a clean or rebuild, rather
# than trusting the Reflector to do it. Same here.
#
# Note the directory name: the Reflector writes _AutoGenerated, with a capital G, while
# Esoterica.props writes _Autogenerated. On Windows those are the same directory and on Linux
# they are not, so this matches case-insensitively rather than picking one.
clean_autogenerated_files()
{
    local -a directories
    mapfile -t directories < <(
        find "${REPO_ROOT}/Code" -type d -ipath '*/_Module/_autogenerated' 2>/dev/null | sort )

    if [[ ${#directories[@]} -eq 0 ]]
    then
        echo "==> no autogenerated directories to clean"
        return
    fi

    for directory in "${directories[@]}"
    do
        echo "==> cleaning ${directory#${REPO_ROOT}/}"
        find "${directory}" -mindepth 1 -delete
    done
}

#-------------------------------------------------------------------------

main()
{
    local mode="${1:-}"

    if [[ ! -x "${REFLECTOR_EXE}" ]]
    then
        echo "error: ${REFLECTOR_EXE#${REPO_ROOT}/} does not exist." >&2
        echo "       Build it first:" >&2
        echo "         ninja -f Build/Linux/Esoterica.ninja Build/Linux_Release/Esoterica.Applications.Reflector" >&2
        exit 1
    fi

    case "${mode}" in
        --clean|-clean|clean)
            clean_autogenerated_files
            "${REFLECTOR_EXE}" -s "${SOLUTION_PATH}" "${REFLECTOR_ARGS[@]}" -clean
            ;;
        --rebuild|-rebuild|rebuild)
            clean_autogenerated_files
            "${REFLECTOR_EXE}" -s "${SOLUTION_PATH}" "${REFLECTOR_ARGS[@]}" -rebuild
            ;;
        '')
            "${REFLECTOR_EXE}" -s "${SOLUTION_PATH}" "${REFLECTOR_ARGS[@]}"
            ;;
        *)
            echo "error: unknown option \"${mode}\". Use --clean, --rebuild, or no argument." >&2
            exit 1
            ;;
    esac
}

main "$@"
