"""Generates Build/Linux/Esoterica.ninja and compile_commands.json.

    python3 Code/Scripts/NinjaGen/NinjaGen.py
    ninja -f Build/Linux/Esoterica.ninja

The build model comes from the three source lists (SourceLists.py), and the flags come from the
property sheet translation (Toolchain.py). This file does the emitting, and nothing else.

It refuses to run when UpstreamProjects.txt no longer matches the Visual Studio projects. That
check is what keeps a new upstream source from joining the build unnoticed, so it is not
optional and there is no flag to skip it.

Output layout mirrors MSBuild's, which Esoterica.props sets as Build/$(Platform)_$(Configuration):

    Build/Linux/Esoterica.ninja           the build file
    Build/Linux_<Config>/                 binaries
    Build/_Temp/Linux_<Config>/<Project>/ object files
"""

import argparse
import subprocess
import sys

from pathlib import Path

sys.path.insert( 0, str( Path( __file__ ).resolve().parent ) )

import SourceLists
import SyncUpstream
import Toolchain

from ninja_syntax import Writer

#-------------------------------------------------------------------------

SHADER_REGISTRATION_DIRECTORY = 'Code/Engine/_Module/_AutoGenerated/Shaders'

NINJA_DIRECTORY = 'Build/Linux'
NINJA_FILE      = 'Build/Linux/Esoterica.ninja'
OUTPUT_PREFIX   = 'Build/Linux'
TEMP_PREFIX     = 'Build/_Temp/Linux'

#-------------------------------------------------------------------------

SHADER_REGISTRATION_HEADER = """\
// Placeholder written by NinjaGen.py. Not the Reflector's output.
//
// Engine/Render/RenderSystem.cpp includes this unconditionally, so the Engine does not compile
// without it, and nothing links against the Engine either - including the ResourceCompiler,
// which never renders anything.
//
// The real file is generated by the Reflector's shader pass, which needs DXC to compile every
// .esh first. 23 of the 28 shaders now compile. The other five assign a RWStructuredBuffer from
// ResourceDescriptorHeap, which DXC's SPIR-V back end cannot associate a counter variable for,
// and the pass writes nothing unless all of them succeed.
//
// This is not about bindless, which compiles fine. See the 2026-08-28 entries in
// Docs/Linux/Progress.md for what the defect actually is, and for an approach that looks
// obvious, passes spirv-val, and is silently wrong.
//
// An empty shader list is the honest stand-in. Shaders::Initialize registers nothing, so a Linux
// build that actually tried to draw would render nothing rather than draw something wrong.
//
// The Reflector overwrites this the moment its shader pass succeeds, and NinjaGen.py reports the
// placeholder on every run until it does.

#pragma once

#include "Engine/Render/Shaders/EngineShader.h"
#include "Base/Render/RHI.h"

//-------------------------------------------------------------------------

namespace EE::Render::Shaders
{
    void Initialize( RHI::Context* pContextRHI, TVector<MaterialShader>& materialShaders, TVector<SurfaceShader>& surfaceShaders, TVector<ComputeShader>& computeShaders );
}
"""

SHADER_REGISTRATION_SOURCE = """\
// Placeholder written by NinjaGen.py. See ShaderRegistration.h for why.

#include "ShaderRegistration.h"

//-------------------------------------------------------------------------

namespace EE::Render::Shaders
{
    void Initialize( RHI::Context* pContextRHI, TVector<MaterialShader>& materialShaders, TVector<SurfaceShader>& surfaceShaders, TVector<ComputeShader>& computeShaders )
    {
        // No shaders are registered. See the header.
        (void) pContextRHI;
        (void) materialShaders;
        (void) surfaceShaders;
        (void) computeShaders;
    }
}
"""

def write_shader_registration_placeholder( repo_root ):
    """Writes an empty ShaderRegistration.h/.cpp when the Reflector has not produced one.

    Returns a problem string when the placeholder is in use, and None when the real files are
    present. The problem is reported on every run on purpose: a stale placeholder is exactly the
    kind of failure that leaves a green build behind, so it must never go quiet.

    Only ever writes when the header is missing. The Reflector's output is never overwritten.
    """

    directory = repo_root / SHADER_REGISTRATION_DIRECTORY
    header = directory / 'ShaderRegistration.h'
    source = directory / 'ShaderRegistration.cpp'

    if header.exists() and 'Placeholder written by NinjaGen.py' not in header.read_text():
        return None

    directory.mkdir( parents = True, exist_ok = True )
    header.write_text( SHADER_REGISTRATION_HEADER )
    source.write_text( SHADER_REGISTRATION_SOURCE )

    return ( f'{SHADER_REGISTRATION_DIRECTORY}/ShaderRegistration.h is a placeholder with no '
             'shaders in it. The Reflector\'s shader pass compiles 23 of 28 shaders; the other '
             'five hit a DXC SPIR-V counter-variable defect, and the pass writes nothing unless '
             'all of them succeed. See Docs/Linux/Progress.md. Until then a Linux build renders '
             'nothing.' )

#-------------------------------------------------------------------------

def ninja_identifier( name ):
    """ninja variable and rule names cannot contain a dot."""

    return name.replace( '.', '_' )

def shell_quote( value ):
    """Quotes a define value so the shell passes it through unchanged.

    EASTL_USER_CONFIG_HEADER's value contains double quotes that are part of the macro.
    """

    if any( character in value for character in ' "\'$()' ):
        return "'" + value.replace( "'", """'"'"'""" ) + "'"
    return value

def format_define( define ):
    if isinstance( define, tuple ):
        name, value = define
        return f'-D{name}={shell_quote( value )}'
    return f'-D{define}'

#-------------------------------------------------------------------------

def topological_order( solution, project ):
    """Returns `project`'s dependencies, closest first.

    A static archive has to appear on the link line after everything that needs it, so link
    order is the reverse topological order of the reference graph.
    """

    ordered = []
    seen = set()

    def visit( name ):
        if name in seen:
            return
        seen.add( name )

        dependency = solution.get_project( name )
        if dependency is None:
            return

        ordered.append( dependency )
        for reference in dependency.references:
            visit( reference )

    for reference in project.references:
        visit( reference )

    return ordered

def library_path( project, configuration ):
    """Where a project's library lands, or None when it does not produce one."""

    project_type = project.get_project_type( configuration.base_name )

    if project_type == SourceLists.PROJECT_TYPE_SHARED_LIBRARY:
        return f'{OUTPUT_PREFIX}_{configuration.name}/lib{project.name}.so'
    if project_type == SourceLists.PROJECT_TYPE_STATIC_LIBRARY:
        return f'{OUTPUT_PREFIX}_{configuration.name}/lib{project.name}.a'
    return None

def target_path( project, configuration ):
    project_type = project.get_project_type( configuration.base_name )

    if project_type == SourceLists.PROJECT_TYPE_EXECUTABLE:
        return f'{OUTPUT_PREFIX}_{configuration.name}/{project.name}'
    return library_path( project, configuration )

#-------------------------------------------------------------------------

def project_compile_flags( repo_root, project, configuration, problems ):
    """Every flag that compiling this project in this configuration needs."""

    sheets = project.get_property_sheets( configuration.base_name )
    sheet_includes, sheet_defines, _, sheet_problems = Toolchain.resolve_sheets( sheets, repo_root )
    problems.extend( f'{project.name}: {p}' for p in sheet_problems )

    include_directories = list( Toolchain.ESOTERICA_INCLUDE_DIRECTORIES ) + sheet_includes

    for missing in Toolchain.missing_include_directories( repo_root, include_directories ):
        problems.append( f'{project.name}: include directory "{missing}" does not exist.' )

    defines = [ Toolchain.project_define( project.name ) ]
    defines += list( Toolchain.COMMON_DEFINES )
    defines += list( Toolchain.ESOTERICA_DEFINES )
    defines += list( configuration.defines )
    defines += list( sheet_defines )

    flags = [ format_define( d ) for d in defines ]
    flags += [ f'-I{directory}' for directory in include_directories ]
    flags += list( Toolchain.COMMON_COMPILER_FLAGS )
    flags += list( configuration.compiler_flags )

    # No -fvisibility=hidden. It looks right, and it is wrong here.
    #
    # The export macros this codebase uses are a Windows DLL mechanism. _Module/API.h now has a
    # visibility( "default" ) branch for Linux, but the vendored imgui and EASTL headers define
    # IMGUI_API and EASTL_API as __declspec, which clang parses and then ignores on ELF. Under
    # -fvisibility=hidden those symbols would be hidden, and Engine and EngineTools would fail
    # to link against them. Code/**/ThirdParty cannot be edited (Conventions rule 5).
    #
    # Default visibility for everything is the ordinary ELF behaviour, and it is what the
    # dllexport model approximates on Windows. Phase 5 or 7 can revisit this if .so load time
    # ever matters.

    return flags

def project_link_flags( repo_root, solution, project, configuration, problems ):
    """Link flags for a project, including the sheets of everything it depends on."""

    sheets = list( project.get_property_sheets( configuration.base_name ) )

    for dependency in topological_order( solution, project ):
        for sheet in dependency.get_property_sheets( configuration.base_name ):
            if sheet not in sheets:
                sheets.append( sheet )

    _, _, link_flags, sheet_problems = Toolchain.resolve_sheets( sheets, repo_root )
    problems.extend( f'{project.name}: {p}' for p in sheet_problems )

    flags = list( configuration.linker_flags )

    # Replaces the MSBuild Copy targets, such as DXC_CopyDLL, that stage DLLs beside the
    # executable. rpath has fewer moving parts than a staging step.
    flags.append( "-Wl,-rpath,'$$ORIGIN'" )

    # -rdynamic puts the executable's own symbols in the dynamic table, which is what lets the
    # crash handler in Platform_Linux.cpp print function names instead of bare addresses.
    # Without it a backtrace is close to useless.
    flags.append( '-rdynamic' )
    flags.extend( link_flags )

    return flags

#-------------------------------------------------------------------------

def object_path( project, configuration, source ):
    """Object paths derive from the repo-relative source path, never an absolute one.

    An absolute path here would make the build directory unusable on any other machine.
    """

    return f'{TEMP_PREFIX}_{configuration.name}/{project.name}/{source}.o'

def emit( repo_root, solution, configurations ):
    """Writes the ninja file. Returns ( text, problems, debug_rule_names )."""

    problems = []
    debug_rule_names = []

    from io import StringIO
    output = StringIO()
    writer = Writer( output, 100 )

    writer.comment( 'GENERATED FILE - regenerate with python3 Code/Scripts/NinjaGen/NinjaGen.py' )
    writer.comment( 'Source of truth: Code/Scripts/NinjaGen/{UpstreamProjects,Exclusions,LinuxSources}.txt' )
    writer.newline()

    writer.variable( 'ninja_required_version', '1.10' )
    writer.newline()

    writer.variable( 'cc', Toolchain.COMPILER_C )
    writer.variable( 'cxx', Toolchain.COMPILER_CPP )
    writer.variable( 'ld', Toolchain.LINKER )
    writer.variable( 'ar', Toolchain.ARCHIVER )
    writer.newline()

    writer.variable( 'c_std', ' '.join( Toolchain.C_FLAGS ) )
    writer.variable( 'cpp_std', ' '.join( Toolchain.CPP_FLAGS ) )
    writer.newline()

    default_targets = []

    for configuration in configurations:
        writer.comment( '-' * 71 )
        writer.comment( f'Configuration: {configuration.name}' )
        writer.comment( '-' * 71 )
        writer.newline()

        writer.rule( f'ar_{configuration.name}',
                     command = '$ar rcs $out $in',
                     description = f'AR {configuration.name} $out' )

        for project in sorted( solution.projects, key = lambda p: p.name ):
            if not project.builds_in( configuration.base_name ):
                continue

            identifier = f'{ninja_identifier( project.name )}_{configuration.name}'

            compile_flags = project_compile_flags( repo_root, project, configuration, problems )
            flag_text = ' '.join( compile_flags )

            # One rule per project and configuration, with the flags baked in. The alternative
            # is a per-edge variable, which doubles the size of the file for no gain.
            writer.rule( f'cc_{identifier}',
                         command = f'$cc -MMD -MF $out.d $c_std {flag_text} -c $in -o $out',
                         description = f'CC {configuration.name} $out',
                         depfile = '$out.d', deps = 'gcc' )
            writer.rule( f'cxx_{identifier}',
                         command = f'$cxx -MMD -MF $out.d $cpp_std {flag_text} -c $in -o $out',
                         description = f'CXX {configuration.name} $out',
                         depfile = '$out.d', deps = 'gcc' )

            if configuration.name == 'Debug':
                debug_rule_names.append( f'cc_{identifier}' )
                debug_rule_names.append( f'cxx_{identifier}' )

            object_files = []

            for source in project.sources:
                out = object_path( project, configuration, source )
                extension = Path( source ).suffix.lower()
                rule = ( f'cc_{identifier}' if extension in SourceLists.C_SOURCE_EXTENSIONS
                         else f'cxx_{identifier}' )
                writer.build( out, rule, source )
                object_files.append( out )

            writer.newline()

            output_path = target_path( project, configuration )
            if output_path is None:
                problems.append( f'{project.name}: no output type for '
                                 f'{configuration.base_name}. Nothing is linked.' )
                continue

            # An empty source list is normal in Phase 0. Esoterica.Applications.Engine has only
            # a Win32 entry point until Phase 6 adds the Linux one.
            if not object_files:
                problems.append( f'{project.name}: no sources in {configuration.name}. '
                                 f'{output_path} is not built.' )
                continue

            project_type = project.get_project_type( configuration.base_name )

            if project_type == SourceLists.PROJECT_TYPE_STATIC_LIBRARY:
                writer.build( output_path, f'ar_{configuration.name}', object_files )
            else:
                dependencies = topological_order( solution, project )
                dependency_libraries = [ library_path( d, configuration ) for d in dependencies ]
                dependency_libraries = [ p for p in dependency_libraries if p is not None ]

                link_flags = project_link_flags( repo_root, solution, project, configuration, problems )
                shared = project_type == SourceLists.PROJECT_TYPE_SHARED_LIBRARY

                rule_name = ( f'so_{identifier}' if shared else f'exe_{identifier}' )
                shared_flag = '-shared ' if shared else ''

                writer.rule( rule_name,
                             command = f'$ld {shared_flag}-o $out $in {" ".join( link_flags )}',
                             description = f'LINK {configuration.name} $out' )
                writer.build( output_path, rule_name, object_files + dependency_libraries )

            writer.newline()

            if configuration.name == 'Debug':
                default_targets.append( output_path )

    if default_targets:
        writer.comment( 'Building with no target named builds every Debug target.' )
        writer.default( default_targets )

    # Writer.close() closes the underlying stream, so take the text first.
    text = output.getvalue()
    writer.close()
    return text, problems, debug_rule_names

#-------------------------------------------------------------------------

def write_compile_commands( repo_root, rule_names ):
    """Generates compile_commands.json for clangd.

    Only the Debug rules go in. Every configuration compiles the same files, and a duplicated
    entry per configuration would make the file nine times larger for no benefit.
    """

    result = subprocess.run(
        [ 'ninja', '-f', NINJA_FILE, '-t', 'compdb' ] + rule_names,
        cwd = repo_root, capture_output = True, text = True )

    if result.returncode != 0:
        return False, result.stderr.strip()

    ( repo_root / 'compile_commands.json' ).write_text( result.stdout )
    return True, ''

#-------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser( description = __doc__ )
    parser.add_argument( '--no-compdb', action = 'store_true',
                         help = 'skip compile_commands.json' )
    arguments = parser.parse_args()

    repo_root = SourceLists.find_repo_root()

    # The staleness check comes first, and there is no way to skip it. See the module docstring.
    sync = subprocess.run( [ sys.executable, 'Code/Scripts/NinjaGen/SyncUpstream.py' ],
                           cwd = repo_root, capture_output = True, text = True )
    if sync.returncode != 0:
        sys.stderr.write( sync.stdout )
        sys.stderr.write( sync.stderr )
        return 1

    # Before loading the source lists: the placeholder .cpp has to exist for the Shaders glob
    # in SourceLists.glob_autogenerated_sources to pick it up.
    placeholder_problem = write_shader_registration_placeholder( repo_root )

    solution, list_problems = SourceLists.load( repo_root )
    configurations = Toolchain.build_configurations( solution.configurations )

    text, emit_problems, debug_rules = emit( repo_root, solution, configurations )

    ( repo_root / NINJA_DIRECTORY ).mkdir( parents = True, exist_ok = True )
    ( repo_root / NINJA_FILE ).write_text( text )

    source_count = sum( len( p.sources ) for p in solution.projects )
    print( f'wrote {NINJA_FILE}: {len( solution.projects )} projects, {source_count} sources, '
           f'{len( configurations )} configurations.' )

    if not arguments.no_compdb:
        ok, error = write_compile_commands( repo_root, debug_rules )
        if ok:
            print( 'wrote compile_commands.json' )
        else:
            emit_problems.append( f'compile_commands.json failed: {error}' )

    # The same problem repeats once per configuration, so report each distinct one once.
    problems = []
    for problem in list_problems + emit_problems + ( [ placeholder_problem ] if placeholder_problem else [] ):
        if problem not in problems:
            problems.append( problem )

    for problem in problems:
        print( f'problem: {problem}', file = sys.stderr )

    # Problems are reported, not fatal. Several are expected in Phase 0: dependencies that do
    # not arrive until a later phase, and projects whose only source is a Win32 entry point.
    print( f'{len( problems )} problem(s).' )
    return 0

if __name__ == '__main__':
    sys.exit( main() )
