"""The three source lists that define the Linux build, and the model built from them.

    UpstreamProjects.txt   generated. Never edit by hand. Projects, per-configuration types,
                           references, property sheets, and every upstream source.
    Exclusions.txt         hand-maintained. Globs for upstream sources the Linux build drops.
    LinuxSources.txt       hand-maintained. Sources this fork adds.

The build reads these three text files and no XML. `SyncUpstream.py` is the only thing that
reads the Visual Studio project files, and it runs when upstream changes, not on every build.

Why lists rather than deriving the source list from the .vcxproj files on every build: upstream
churns about five source-list entries a year, so live parsing bought almost nothing and cost a
pile of filename heuristics. Docs/Linux/Progress.md records the measurement and the decision.
"""

import re
import sys

from pathlib import Path

#-------------------------------------------------------------------------

SOURCE_LISTS_DIRECTORY = 'Code/Scripts/NinjaGen'

UPSTREAM_PROJECTS_FILE = 'UpstreamProjects.txt'
EXCLUSIONS_FILE        = 'Exclusions.txt'
LINUX_SOURCES_FILE     = 'LinuxSources.txt'

PROJECT_TYPE_SHARED_LIBRARY = 'SharedLibrary'
PROJECT_TYPE_STATIC_LIBRARY = 'StaticLibrary'
PROJECT_TYPE_EXECUTABLE     = 'Executable'
PROJECT_TYPE_NMAKE          = 'NMake'

C_SOURCE_EXTENSIONS   = ( '.c', )
CPP_SOURCE_EXTENSIONS = ( '.cpp', '.cc', '.cxx' )

# Esoterica.props adds these as MSBuild wildcards, so no .vcxproj lists them. They are Reflector
# outputs, regenerated on every reflection run, so they stay globbed rather than listed.
AUTOGENERATED_GLOBS = (
    ( '_Module', '_Autogenerated', 'TypeInfo' ),
    ( '_Module', '_Autogenerated', 'Shaders' ),
)

#-------------------------------------------------------------------------
# Glob matching
#-------------------------------------------------------------------------

def compile_glob( pattern ):
    """Turns a path glob into a regex.

    `fnmatch` treats '*' as matching '/' too, which makes '**' meaningless. These lists need the
    usual distinction, so translate by hand:

        **/     zero or more leading directories
        **      anything, including '/'
        *       anything except '/'
        ?       one character except '/'
    """

    result = ''
    index = 0

    while index < len( pattern ):
        if pattern.startswith( '**/', index ):
            result += '(?:.*/)?'
            index += 3
        elif pattern.startswith( '**', index ):
            result += '.*'
            index += 2
        elif pattern[index] == '*':
            result += '[^/]*'
            index += 1
        elif pattern[index] == '?':
            result += '[^/]'
            index += 1
        else:
            result += re.escape( pattern[index] )
            index += 1

    return re.compile( f'^{result}$' )

class GlobList:
    """A list of globs, with a record of which ones actually matched something.

    The record matters: a glob that matches nothing is usually a stale entry left behind by an
    upstream rename, and it should not sit in the file unnoticed.
    """

    def __init__( self, patterns ):
        self.patterns = list( patterns )
        self.compiled = [ compile_glob( p ) for p in self.patterns ]
        self.matched = set()

    def matches( self, path ):
        # Every pattern is checked, not just up to the first hit, so that `unused_patterns`
        # stays accurate when two globs overlap.
        result = False

        for pattern, compiled in zip( self.patterns, self.compiled ):
            if compiled.match( path ):
                self.matched.add( pattern )
                result = True

        return result

    def unused_patterns( self ):
        return [ p for p in self.patterns if p not in self.matched ]

#-------------------------------------------------------------------------
# Model
#-------------------------------------------------------------------------

class Project:
    def __init__( self, name ):
        self.name = name
        self.project_file = ''              # repo-relative .vcxproj path, for reference only
        self.directory = ''                 # repo-relative

        self.configuration_types = {}       # configuration -> PROJECT_TYPE_*
        self.skipped_configurations = set() # from <Build ... Project="false"/> in the .slnx
        self.references = []                # project names
        self.property_sheets = {}           # configuration -> [ sheet name ]

        self.upstream_sources = []          # project-relative, as listed in UpstreamProjects.txt
        self.excluded_sources = []          # dropped by Exclusions.txt
        self.linux_sources = []             # from LinuxSources.txt
        self.autogenerated_sources = []     # globbed at load time

    #-------------------------------------------------------------------------

    def builds_in( self, configuration ):
        if configuration in self.skipped_configurations:
            return False
        return self.get_project_type( configuration ) not in ( None, PROJECT_TYPE_NMAKE )

    def get_project_type( self, configuration ):
        return self.configuration_types.get( configuration )

    def get_property_sheets( self, configuration ):
        return self.property_sheets.get( configuration, [] )

    def to_repo_path( self, project_relative_path ):
        return f'{self.directory}/{project_relative_path}'

    #-------------------------------------------------------------------------

    @property
    def sources( self ):
        """Every source the Linux build compiles for this project, repo-relative and sorted."""

        kept = [ self.to_repo_path( s ) for s in self.upstream_sources ]
        kept += [ self.to_repo_path( s ) for s in self.linux_sources ]
        return sorted( set( kept + self.autogenerated_sources ) )

    @property
    def c_sources( self ):
        return [ s for s in self.sources if Path( s ).suffix.lower() in C_SOURCE_EXTENSIONS ]

    @property
    def cpp_sources( self ):
        return [ s for s in self.sources if Path( s ).suffix.lower() in CPP_SOURCE_EXTENSIONS ]

class Solution:
    def __init__( self ):
        self.configurations = []
        self.platform = ''
        self.projects = []

    def get_project( self, name ):
        for project in self.projects:
            if project.name == name:
                return project
        return None

#-------------------------------------------------------------------------
# UpstreamProjects.txt
#-------------------------------------------------------------------------

UPSTREAM_HEADER = """\
# GENERATED FILE - DO NOT EDIT BY HAND.
#
# Regenerate with:   python3 Code/Scripts/NinjaGen/SyncUpstream.py --update
# Check it is current: python3 Code/Scripts/NinjaGen/SyncUpstream.py
#
# This is the Linux build's snapshot of the Visual Studio projects: every source upstream
# builds, plus the per-configuration facts the generator needs. The build reads this file
# instead of parsing XML, so a new upstream source cannot enter the build unreviewed.
#
# Hand edits belong in the other two lists:
#   Exclusions.txt    upstream sources the Linux build drops
#   LinuxSources.txt  sources this fork adds
#
# Source paths are relative to each project's directory, and are the real on-disk spelling.
# Some .vcxproj entries disagree with the case on disk, which Windows ignores and Linux does
# not, so the sync corrects them here once rather than at every build.
"""

def parse_upstream_projects( text ):
    """Reads UpstreamProjects.txt.

    Line-oriented on purpose. One fact per line means a merge conflict lands on the one entry
    that changed, and a diff is readable without a tool.
    """

    solution = Solution()
    project = None

    for line_number, raw_line in enumerate( text.splitlines(), start = 1 ):
        line = raw_line.split( '#', 1 )[0].strip()
        if not line:
            continue

        keyword, _, remainder = line.partition( ' ' )
        remainder = remainder.strip()

        if keyword == 'configurations':
            solution.configurations = remainder.split()

        elif keyword == 'platform':
            solution.platform = remainder

        elif keyword == 'project':
            project = Project( remainder )
            solution.projects.append( project )

        elif project is None:
            raise RuntimeError(
                f'{UPSTREAM_PROJECTS_FILE}:{line_number}: "{keyword}" before any project.' )

        elif keyword == 'file':
            project.project_file = remainder
            project.directory = str( Path( remainder ).parent.as_posix() )

        elif keyword == 'type':
            configuration, _, project_type = remainder.partition( ' ' )
            project.configuration_types[configuration] = project_type.strip()

        elif keyword == 'skip':
            project.skipped_configurations.add( remainder )

        elif keyword == 'ref':
            project.references.append( remainder )

        elif keyword == 'sheet':
            configuration, _, sheets = remainder.partition( ' ' )
            project.property_sheets[configuration] = sheets.split()

        elif keyword == 'src':
            project.upstream_sources.append( remainder )

        else:
            raise RuntimeError(
                f'{UPSTREAM_PROJECTS_FILE}:{line_number}: unknown keyword "{keyword}".' )

    return solution

def format_upstream_projects( solution ):
    """Writes UpstreamProjects.txt. Deterministic: same input, byte-identical output."""

    lines = [ UPSTREAM_HEADER ]
    lines.append( f'configurations {" ".join( solution.configurations )}' )
    lines.append( f'platform {solution.platform}' )
    lines.append( '' )

    for project in sorted( solution.projects, key = lambda p: p.name ):
        lines.append( f'project {project.name}' )
        lines.append( f'  file {project.project_file}' )

        for configuration in solution.configurations:
            project_type = project.get_project_type( configuration )
            if project_type is not None:
                lines.append( f'  type {configuration} {project_type}' )

        for configuration in solution.configurations:
            if configuration in project.skipped_configurations:
                lines.append( f'  skip {configuration}' )

        for reference in project.references:
            lines.append( f'  ref {reference}' )

        for configuration in solution.configurations:
            sheets = project.get_property_sheets( configuration )
            if sheets:
                lines.append( f'  sheet {configuration} {" ".join( sheets )}' )

        for source in sorted( project.upstream_sources ):
            lines.append( f'  src {source}' )

        lines.append( '' )

    return '\n'.join( lines ).rstrip( '\n' ) + '\n'

#-------------------------------------------------------------------------
# Exclusions.txt and LinuxSources.txt
#-------------------------------------------------------------------------

def parse_glob_list( text ):
    patterns = []

    for raw_line in text.splitlines():
        line = raw_line.split( '#', 1 )[0].strip()
        if line:
            patterns.append( line )

    return GlobList( patterns )

def parse_linux_sources( text ):
    """Reads LinuxSources.txt: [Project] sections, one project-relative path per line."""

    sources = {}
    project_name = None

    for line_number, raw_line in enumerate( text.splitlines(), start = 1 ):
        line = raw_line.split( '#', 1 )[0].strip()
        if not line:
            continue

        if line.startswith( '[' ) and line.endswith( ']' ):
            project_name = line[1:-1].strip()
            sources.setdefault( project_name, [] )
            continue

        if project_name is None:
            raise RuntimeError(
                f'{LINUX_SOURCES_FILE}:{line_number}: "{line}" before any [Project] section.' )

        sources[project_name].append( line )

    return sources

#-------------------------------------------------------------------------
# Loading
#-------------------------------------------------------------------------

def resolve_directory_ignoring_case( root, parts ):
    current = root

    for part in parts:
        if not current.is_dir():
            return None

        match = None
        for entry in sorted( current.iterdir() ):
            if entry.is_dir() and entry.name.lower() == part.lower():
                match = entry
                break

        if match is None:
            return None
        current = match

    return current

def glob_autogenerated_sources( repo_root, project_directory ):
    """Finds the Reflector's output for a project.

    Upstream spells the directory '_Autogenerated' in Esoterica.props and '_AutoGenerated' in
    Reflect.nmake. The real one on disk is '_AutoGenerated'. Match case-insensitively so both
    spellings work, and treat an absent directory as normal: it does not exist until the
    Reflector has run.
    """

    found = []
    project_absolute = repo_root / project_directory

    for parts in AUTOGENERATED_GLOBS:
        directory = resolve_directory_ignoring_case( project_absolute, parts )
        if directory is None:
            continue

        for entry in sorted( directory.iterdir() ):
            if entry.is_file() and entry.suffix.lower() == '.cpp':
                found.append( entry.relative_to( repo_root ).as_posix() )

    return sorted( found )

def find_repo_root():
    return Path( __file__ ).resolve().parents[3]

def load( repo_root = None, apply_exclusions = True, glob_autogenerated = True ):
    """Loads the three lists into a Solution.

    Returns ( solution, problems ). `problems` is a list of strings. It is empty on a healthy
    tree. The caller decides whether a problem is fatal.
    """

    if repo_root is None:
        repo_root = find_repo_root()

    lists_directory = repo_root / SOURCE_LISTS_DIRECTORY

    solution = parse_upstream_projects(
        ( lists_directory / UPSTREAM_PROJECTS_FILE ).read_text() )
    exclusions = parse_glob_list(
        ( lists_directory / EXCLUSIONS_FILE ).read_text() )
    linux_sources = parse_linux_sources(
        ( lists_directory / LINUX_SOURCES_FILE ).read_text() )

    solution.exclusions = exclusions
    problems = []

    for project in solution.projects:
        if apply_exclusions:
            kept = []
            for source in project.upstream_sources:
                if exclusions.matches( project.to_repo_path( source ) ):
                    project.excluded_sources.append( source )
                else:
                    kept.append( source )
            project.upstream_sources = kept

        project.linux_sources = linux_sources.pop( project.name, [] )

        if glob_autogenerated:
            project.autogenerated_sources = glob_autogenerated_sources(
                repo_root, project.directory )

        for source in project.linux_sources:
            if not ( repo_root / project.to_repo_path( source ) ).is_file():
                problems.append(
                    f'{LINUX_SOURCES_FILE}: [{project.name}] lists "{source}", '
                    f'which does not exist.' )

    for project_name in sorted( linux_sources ):
        problems.append(
            f'{LINUX_SOURCES_FILE}: [{project_name}] is not a project in '
            f'{UPSTREAM_PROJECTS_FILE}.' )

    if apply_exclusions:
        for pattern in exclusions.unused_patterns():
            problems.append(
                f'{EXCLUSIONS_FILE}: "{pattern}" matches nothing. It is probably stale.' )

    return solution, problems

#-------------------------------------------------------------------------

def main():
    solution, problems = load()

    print( f'configurations: {" ".join( solution.configurations )}' )
    print( f'platform:       {solution.platform}' )
    print()

    for project in sorted( solution.projects, key = lambda p: p.name ):
        types = ' '.join( f'{c}={project.get_project_type( c ) or "-"}'
                          for c in solution.configurations )
        built = ', '.join( c for c in solution.configurations if project.builds_in( c ) )

        print( f'{project.name}' )
        print( f'  type      {types}' )
        print( f'  builds    {built or "never"}' )
        print( f'  sources   {len( project.sources )} '
               f'({len( project.upstream_sources )} upstream, '
               f'{len( project.linux_sources )} linux, '
               f'{len( project.autogenerated_sources )} autogenerated, '
               f'{len( project.excluded_sources )} excluded)' )

        if project.references:
            print( f'  refs      {", ".join( project.references )}' )
        print()

    for problem in problems:
        print( f'problem: {problem}', file = sys.stderr )

    print( f'{len( problems )} problem(s).' )
    return 1 if problems else 0

if __name__ == '__main__':
    sys.exit( main() )
