#!/usr/bin/env python3
"""Emit a normalised structural summary of the Reflector's generated shader code.

Phase 4 acceptance criterion 6 asks for a structural diff of this output against the
Windows-generated output, with the bytecode ignored, because SPIR-V is not DXIL and the two
will never be byte-identical. This produces the thing to diff.

    python3 Code/Scripts/ShaderStructure/ExtractShaderStructure.py \
        Code/Engine/_Module/_AutoGenerated/Shaders > linux.txt

Run it on both platforms and diff the two files. Anything that differs is a real structural
divergence: a missing shader, a stage that reflected differently, a parameter struct whose
members or defaults changed. Nothing bytecode-dependent survives into the output.

What is removed, and why:

  - the base85 payload lines, which are the compressed bytecode itself
  - the three g_byteCode_*_{decompressed,decoded,compressed}Size constants, whose values are
    sizes of that bytecode
  - the array bound in `static char const g_byteCode_X[9501]`, same reason
  - the "Generated For:" line, which is an absolute path and differs per checkout

Everything else is kept verbatim, with whitespace collapsed so that formatting differences do
not show up as structural ones. Keeping the rest verbatim rather than parsing it is deliberate:
a parser only compares what it was taught to look for, and this has to catch what nobody
predicted.
"""

import os
import re
import sys

BYTECODE_SIZE_CONSTANT = re.compile(
    r"^constexpr uint32_t g_byteCode_\w+_(decompressedSize|decodedSize|compressedSize) = \d+;$" )
BYTECODE_ARRAY_BOUND = re.compile( r"(g_byteCode_\w+)\[\d+\]" )
STRING_LITERAL_LINE = re.compile( r'^"' )
GENERATED_FOR = re.compile( r"^// Generated For:" )


def normalise( path ):
    lines = []
    with open( path, encoding = "utf-8" ) as handle:
        for raw in handle:
            line = " ".join( raw.split() )
            if not line:
                continue
            if STRING_LITERAL_LINE.match( line ):
                continue
            if BYTECODE_SIZE_CONSTANT.match( line ):
                continue
            if GENERATED_FOR.match( line ):
                continue
            lines.append( BYTECODE_ARRAY_BOUND.sub( r"\1[]", line ) )
    return lines


def main():
    if len( sys.argv ) != 2:
        sys.exit( f"usage: {sys.argv[0]} <generated shaders directory>" )

    directory = sys.argv[1]
    if not os.path.isdir( directory ):
        sys.exit( f"error: {directory} is not a directory" )

    names = sorted( f for f in os.listdir( directory ) if f.endswith( ( ".cpp", ".h" ) ) )
    if not names:
        sys.exit( f"error: {directory} holds no generated .cpp or .h files" )

    out = sys.stdout
    out.write( f"# {len( names )} generated files\n" )
    for name in names:
        out.write( f"file: {name}\n" )
    for name in names:
        out.write( f"\n===== {name} =====\n" )
        for line in normalise( os.path.join( directory, name ) ):
            out.write( line + "\n" )


if __name__ == "__main__":
    main()
