#!/usr/bin/env python3
#
# Compile every translation unit in the tree and attribute each warning to whoever owns the file.
#
# The Linux build is warning-free, and staying that way needs a way to check. `ninja` cannot do it:
# it only recompiles what changed, so a green incremental build says nothing about the other 880
# files. This script recompiles all of them with -fsyntax-only, which is fast enough to run after a
# merge and touches no build output.
#
# Usage:
#   python3 Docs/Linux/Scripts/WarningSweep.py                 sweep, and print a summary
#   python3 Docs/Linux/Scripts/WarningSweep.py --by-flag        also break the total down per flag
#   python3 Docs/Linux/Scripts/WarningSweep.py --list           print every unique site
#   python3 Docs/Linux/Scripts/WarningSweep.py --audit-fork     re-enable the warnings this fork's
#                                                               tier suppresses, and report only its
#                                                               own files
#
# Exits 1 if any warning is reported, so it can gate a merge.
#
#-------------------------------------------------------------------------
# What it measures, and why the ownership split is the whole point
#
# The first sweep, on 2026-09-04, found 85,097 diagnostics at 17,264 unique sites - and 99.3% of
# those sites were upstream's or the Reflector's rather than this fork's:
#
#   Reflector-generated code       15,366   89.0%
#   upstream first-party source     1,459    8.5%
#   external dependency headers       264    1.5%
#   this fork's own files             114    0.7%
#   vendored third-party               61    0.4%
#
# That measurement is what Toolchain.py's three warning tiers are built on. A raw count is not
# useful on its own: -Wdeprecated-builtins was 25,560 diagnostics from 8 EASTL header sites, one per
# translation unit that included the header. Unique sites are the number that means something.
#
# --audit-fork exists because the fork tier suppresses -Wunused-parameter. It has to: upstream
# headers leak 199 of them into this fork's translation units and clang has no per-header
# suppression that would not also cover this fork's own headers under Code/. So the build cannot
# catch an unused parameter in new Linux code, and this is how to look for one deliberately.
#
#-------------------------------------------------------------------------
# Requirements
#
#   External/LLVM/bin on PATH, and compile_commands.json current:
#
#     export PATH="$PWD/External/LLVM/bin:$PATH"
#     python3 Code/Scripts/NinjaGen/NinjaGen.py
#
# compile_commands.json carries the Debug configuration only, which is what NinjaGen.py writes. The
# optimised configurations can warn about things -O0 cannot see, so this is a floor rather than a
# proof for Release and Shipping.

import argparse
import collections
import json
import os
import re
import shlex
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

REPO_ROOT = Path( __file__ ).resolve().parents[3]

# The flags Toolchain.FORK_WARNING_FLAGS turns off for this fork's own sources. --audit-fork drops
# them from the command line so that the sweep sees what the build deliberately does not.
#
# -Werror goes with them, and that is not cosmetic: leave it in and every re-enabled warning is
# reported as `error:` instead, which this script's pattern does not match. It would then print
# "no warnings" over a compile that failed.
FORK_SUPPRESSIONS = (
    '-Werror',
    '-Wno-unused-parameter',
    '-Wno-unused-function',
    '-Wno-missing-field-initializers',
    '-Wno-missing-designated-field-initializers',
)

WARNING_PATTERN = re.compile(
    r'^([^\s:][^:]*):(\d+):(\d+): warning: (.*?)(?: \[(-W[\w-]+)\])?$', re.M )

#-------------------------------------------------------------------------

def fork_owned_sources():
    """The sources this fork adds, repo-relative.

    Read from LinuxSources.txt through SourceLists rather than re-parsed, so that this script and
    the generator can never disagree about which files are the fork's.
    """

    sys.path.insert( 0, str( REPO_ROOT / 'Code/Scripts/NinjaGen' ) )
    import SourceLists

    solution, _ = SourceLists.load( REPO_ROOT )
    owned = set()

    for project in solution.projects:
        owned.update( project.to_repo_path( s ) for s in project.linux_sources )

    return owned

def owner( path, fork_sources ):
    """Who owns the file a warning was reported in."""

    if path.startswith( '/' ) or 'External/' in path:
        return 'external dependency headers'
    if '/ThirdParty/' in path:
        return 'vendored third-party'
    # Upstream spells this directory both ways; see SourceLists.glob_autogenerated_sources.
    if '_autogenerated/' in path.lower():
        return 'Reflector-generated code'
    if path in fork_sources:
        return "this fork's own files"
    return 'upstream first-party source'

#-------------------------------------------------------------------------

def compile_command( entry, audit_fork ):
    """The entry's command, rewritten to check syntax and write nothing."""

    arguments = shlex.split( entry['command'] )
    kept = []
    index = 0

    while index < len( arguments ):
        argument = arguments[index]

        # -MMD/-MF would write a depfile beside the object, and -o/-c would produce the object.
        if argument == '-MMD' or argument == '-c':
            index += 1
            continue
        if argument in ( '-MF', '-o' ):
            index += 2
            continue
        if audit_fork and argument in FORK_SUPPRESSIONS:
            index += 1
            continue

        kept.append( argument )
        index += 1

    return kept + [ '-fsyntax-only' ]

def sweep( entries, audit_fork, jobs ):
    def run( entry ):
        result = subprocess.run( compile_command( entry, audit_fork ),
                                 capture_output = True, text = True, cwd = entry['directory'] )
        return entry['file'], result.stderr, result.returncode

    with ThreadPoolExecutor( max_workers = jobs ) as executor:
        return list( executor.map( run, entries ) )

#-------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser( description = 'Sweep the tree for compiler warnings.' )
    parser.add_argument( '--by-flag', action = 'store_true',
                         help = 'break the site count down per warning flag' )
    parser.add_argument( '--list', action = 'store_true',
                         help = 'print every unique warning site' )
    parser.add_argument( '--audit-fork', action = 'store_true',
                         help = "re-enable the fork tier's suppressions, and report only its files" )
    parser.add_argument( '-j', '--jobs', type = int, default = os.cpu_count() or 8 )
    arguments = parser.parse_args()

    database = REPO_ROOT / 'compile_commands.json'

    if not database.exists():
        print( f'error: {database} does not exist. Run '
               f'python3 Code/Scripts/NinjaGen/NinjaGen.py first.', file = sys.stderr )
        return 2

    entries = json.loads( database.read_text() )
    fork_sources = fork_owned_sources()

    print( f'sweeping {len( entries )} translation units on {arguments.jobs} jobs...' )
    results = sweep( entries, arguments.audit_fork, arguments.jobs )

    # A header warns once per translation unit that includes it, so the same site is reported many
    # times over. Count sites, and keep the diagnostic total beside it to show the difference.
    sites = {}
    total = 0
    failed = []

    for source, output, exit_code in results:
        if exit_code != 0:
            failed.append( source )

        for path, line, _, message, flag in WARNING_PATTERN.findall( output ):
            if arguments.audit_fork and path not in fork_sources:
                continue
            total += 1
            sites.setdefault( ( path, int( line ), flag or '(no flag)' ), message )

    # A translation unit that does not compile is not a clean one, whatever the warning count says.
    # Say so rather than reporting zero warnings over a broken tree.
    if failed:
        print( f'\n{len( failed )} translation unit(s) failed to compile:' )
        for source in failed[:10]:
            print( f'  {source}' )
        if len( failed ) > 10:
            print( f'  ... and {len( failed ) - 10} more' )

    if not sites:
        scope = "this fork's own files" if arguments.audit_fork else 'the tree'
        print( f'\nno warnings in {scope}.' )
        return 1 if failed else 0

    print( f'\n{total} diagnostics at {len( sites )} unique sites\n' )

    by_owner = collections.Counter( owner( path, fork_sources ) for path, _, _ in sites )

    for name, count in by_owner.most_common():
        print( f'  {count:7d}  {100 * count / len( sites ):5.1f}%  {name}' )

    if arguments.by_flag:
        print()
        for flag, count in collections.Counter( f for _, _, f in sites ).most_common():
            print( f'  {count:7d}  {flag}' )

    if arguments.list:
        print()
        for ( path, line, flag ), message in sorted( sites.items() ):
            print( f'  {path}:{line}: {message} [{flag}]' )

    return 1

if __name__ == '__main__':
    sys.exit( main() )
