#ifdef __linux__
#include "EditorApplication_Linux.h"
#include "EngineTools/_Module/_AutoGenerated/TypeInfo/TypeRegistration.h"
#include "EngineTools/Core/SystemDialogs.h"

// No <SDL3/SDL.h>. Only the address of the event is taken, and Application_Linux.h forward
// declares SDL_Event, so the Editor project does not need the SDL3 include path.

//-------------------------------------------------------------------------

namespace EE
{
    EditorEngine::EditorEngine( TFunction<bool( EE::String const& error )>&& errorHandler )
        : Engine( eastl::forward<TFunction<bool( EE::String const& error )>&&>( errorHandler ) )
    {
        m_modules.emplace_back( EE::New<EngineToolsModule>() );
        m_modules.emplace_back( EE::New<GameModule>() );
        m_modules.emplace_back( EE::New<GameToolsModule>() );
    }

    void EditorEngine::RegisterTypes()
    {
        TypeSystem::Reflection::RegisterTypes( *m_pTypeRegistry );
    }

    void EditorEngine::UnregisterTypes()
    {
        TypeSystem::Reflection::UnregisterTypes( *m_pTypeRegistry );
    }

    void EditorEngine::SetStartupMap( ResourceID const& mapID )
    {
        EE_ASSERT( mapID.IsValid() );
        static_cast<EditorUI*>( m_pToolsUI )->SetStartupMap( mapID );
    }

    //-------------------------------------------------------------------------

    // No HINSTANCE, and no icon resource ID. The Windows build takes its icon and splash screen IDs
    // from a Resource.h that only a .rc file resolves, and nothing here parses those, so
    // LinuxApplication takes file paths that may be null instead.
    //
    // The Borderless flag is kept: the editor draws its own title bar, and LinuxApplication's
    // BorderlessWindowHitTest calls GetBorderlessTitleBarInfo below through SDL_SetWindowHitTest.
    EditorApplication::EditorApplication()
        : LinuxApplication( "Esoterica Editor", nullptr, nullptr, TBitFlags<InitOptions>( LinuxApplication::InitOptions::Borderless ) )
        , m_engine( TFunction<bool( String const& error )>( [this] ( String const& error )-> bool { return FatalError( error ); } ) )
    {}

    void EditorApplication::GetBorderlessTitleBarInfo( Math::ScreenSpaceRectangle& outTitlebarRect, bool& isInteractibleWidgetHovered ) const
    {
        static_cast<EditorUI*>( m_engine.m_pToolsUI )->GetBorderlessTitleBarInfo( outTitlebarRect, isInteractibleWidgetHovered );
    }

    void EditorApplication::ResizeMainWindow( Int2 const& newWindowSize )
    {
        m_engine.ResizeMainWindow( newWindowSize );
    }

    void EditorApplication::ProcessInputEvent( SDL_Event const& event )
    {
        // The event travels by pointer, because GenericMessage is four uint64_t and an SDL_Event is
        // 128 bytes. Sound only because ForwardInputMessageToInputDevices dispatches synchronously,
        // while the event is still on LinuxApplication's stack. Never queue this message for later.
        m_engine.GetInputSystem()->ForwardInputMessageToInputDevices( { (uint64_t) &event, 0, 0, 0 } );
    }

    bool EditorApplication::Initialize( int32_t argc, char** argv )
    {
        // The Win32 sibling derives the dimensions from m_windowRect. LinuxApplication keeps the
        // size and the position apart, and m_windowSize is already in pixels, which is the unit
        // the swapchain wants.
        if ( !m_engine.Initialize( argc, argv, m_windowSize ) )
        {
            return false;
        }

        return true;
    }

    bool EditorApplication::Shutdown()
    {
        return m_engine.Shutdown();
    }

    bool EditorApplication::FatalError( String const& error ) const
    {
        if ( m_engine.m_pToolsUI != nullptr )
        {
            MessageDialog dlg;
            if ( dlg.Confirmation( Severity::FatalError, "Fatal Error Occurred", "A fatal error has occurred and the editor will be shutdown. Do you wish to save any unsaved work?\n\nError: %s", error.c_str() ) )
            {
                auto pEditorUI = static_cast<EditorUI*>( m_engine.m_pToolsUI );
                if ( pEditorUI->HasOpenAndDirtyTools() )
                {
                    pEditorUI->SaveAllDirtyTools();
                }
            }

            return false;
        }
        else
        {
            return LinuxApplication::FatalError( error );
        }
    }

    bool EditorApplication::ApplicationLoop()
    {
        return m_engine.Update();
    }
}

//-------------------------------------------------------------------------

// _tWinMain becomes main, as in EngineApplication_Linux.cpp. __argc and __argv have no
// equivalent and no need for one.
int main( int argc, char** argv )
{
    int result = 0;
    {
        EE::ApplicationGlobalState globalState;
        EE::EditorApplication editorApplication;
        result = editorApplication.Run( argc, argv );
    }

    return result;
}

#endif
